# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
- python=3.6.2

- pip:
  - azureml-train-automl-runtime==1.38.0
  - inference-schema
  - azureml-interpret==1.38.0
  - azureml-defaults==1.38.0
- numpy>=1.16.0,<1.19.0
- pandas==0.25.1
- scikit-learn==0.22.1

